name: track_my_travel
description: A new Flutter project.

version: 0.0.1+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  built_value: ^6.3.1
  built_collection: ^4.1.0
  rxdart: ^0.20.0
  google_maps_flutter: ^0.4.0
  kiwi: ^0.1.0
  shared_preferences: ^0.5.1+1
  permission: ^0.1.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  built_value_generator: ^6.3.0
  test: ^1.5.3
  mockito: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bus_markers/100/1.png
    - assets/bus_markers/100/12.png
    - assets/bus_markers/100/12A.png
    - assets/bus_markers/100/13.png
    - assets/bus_markers/100/14.png
    - assets/bus_markers/100/15.png
    - assets/bus_markers/100/16.png
    - assets/bus_markers/100/19.png
    - assets/bus_markers/100/1A.png
    - assets/bus_markers/100/1G.png
    - assets/bus_markers/100/20.png
    - assets/bus_markers/100/21.png
    - assets/bus_markers/100/22.png
    - assets/bus_markers/100/23.png
    - assets/bus_markers/100/27.png
    - assets/bus_markers/100/28.png
    - assets/bus_markers/100/2.png
    - assets/bus_markers/100/2A.png
    - assets/bus_markers/100/3.png
    - assets/bus_markers/100/4.png
    - assets/bus_markers/100/5.png
    - assets/bus_markers/100/6.png
    - assets/bus_markers/100/7.png
    - assets/bus_markers/100/8.png
    - assets/bus_markers/100/9.png
    - assets/bus_markers/100/X22.png
    - assets/bus_markers/100/default.png

    - assets/bus_markers/150/1.png
    - assets/bus_markers/150/12.png
    - assets/bus_markers/150/12A.png
    - assets/bus_markers/150/13.png
    - assets/bus_markers/150/14.png
    - assets/bus_markers/150/15.png
    - assets/bus_markers/150/X22.png
    - assets/bus_markers/150/16.png
    - assets/bus_markers/150/19.png
    - assets/bus_markers/150/1A.png
    - assets/bus_markers/150/1G.png
    - assets/bus_markers/150/20.png
    - assets/bus_markers/150/21.png
    - assets/bus_markers/150/22.png
    - assets/bus_markers/150/23.png
    - assets/bus_markers/150/27.png
    - assets/bus_markers/150/28.png
    - assets/bus_markers/150/2.png
    - assets/bus_markers/150/2A.png
    - assets/bus_markers/150/3.png
    - assets/bus_markers/150/4.png
    - assets/bus_markers/150/5.png
    - assets/bus_markers/150/6.png
    - assets/bus_markers/150/7.png
    - assets/bus_markers/150/8.png
    - assets/bus_markers/150/9.png
    - assets/bus_markers/150/X22.png
    - assets/bus_markers/150/default.png

    - assets/bus_markers/200/1.png
    - assets/bus_markers/200/12.png
    - assets/bus_markers/200/12A.png
    - assets/bus_markers/200/13.png
    - assets/bus_markers/200/14.png
    - assets/bus_markers/200/15.png
    - assets/bus_markers/200/16.png
    - assets/bus_markers/200/19.png
    - assets/bus_markers/200/1A.png
    - assets/bus_markers/200/1G.png
    - assets/bus_markers/200/20.png
    - assets/bus_markers/200/21.png
    - assets/bus_markers/200/22.png
    - assets/bus_markers/200/23.png
    - assets/bus_markers/200/27.png
    - assets/bus_markers/200/28.png
    - assets/bus_markers/200/2.png
    - assets/bus_markers/200/2A.png
    - assets/bus_markers/200/3.png
    - assets/bus_markers/200/4.png
    - assets/bus_markers/200/5.png
    - assets/bus_markers/200/6.png
    - assets/bus_markers/200/7.png
    - assets/bus_markers/200/8.png
    - assets/bus_markers/200/9.png
    - assets/bus_markers/200/X22.png
    - assets/bus_markers/200/default.png

    - assets/bus_markers/250/1.png
    - assets/bus_markers/250/12.png
    - assets/bus_markers/250/12A.png
    - assets/bus_markers/250/13.png
    - assets/bus_markers/250/14.png
    - assets/bus_markers/250/15.png
    - assets/bus_markers/250/16.png
    - assets/bus_markers/250/19.png
    - assets/bus_markers/250/1A.png
    - assets/bus_markers/250/1G.png
    - assets/bus_markers/250/20.png
    - assets/bus_markers/250/21.png
    - assets/bus_markers/250/22.png
    - assets/bus_markers/250/23.png
    - assets/bus_markers/250/27.png
    - assets/bus_markers/250/28.png
    - assets/bus_markers/250/2.png
    - assets/bus_markers/250/2A.png
    - assets/bus_markers/250/3.png
    - assets/bus_markers/250/4.png
    - assets/bus_markers/250/5.png
    - assets/bus_markers/250/6.png
    - assets/bus_markers/250/7.png
    - assets/bus_markers/250/8.png
    - assets/bus_markers/250/9.png
    - assets/bus_markers/250/X22.png
    - assets/bus_markers/250/default.png
